UISP-46 - Upgrade to react 18 and also leverage jest-config-stripes for all jest and testing library packages
folio-org/ui-servicepoints pull request #139
Opened 2023-08-03 08:37 UTC by Terala-Priyanka

…or all jest and testing library packages

2023-08-03 18:20 UTC, zburke requested changes
Updating the minimum version of a peer-dep (here you are changing react, react-dom, @folio/stripes) is a breaking change. 
* Please change the version in `package.json` from 6.4.0 to 7.0.0.
* Please update CHANGELOG.md and note that this is a breaking change, [e.g. from stripes-core](https://github.com/folio-org/stripes-core/blob/fb9ceb61f58305250200788ea5b7836c3701a500/CHANGELOG.md#L18)

2023-08-03 18:31 UTC, artem-blazhko reviewed
Could you add changes to CHANGELOG file?

2023-08-04 12:05 UTC, zburke approved these changes

2023-08-07 08:18 UTC, Dmitriy-Litvinenko approved these changes

2023-08-07 09:33 UTC, merged